# Generated by Django 3.1.4 on 2020-12-24 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('country', models.CharField(max_length=70)),
                ('life_index', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('size', models.FloatField()),
                ('price', models.FloatField()),
                ('comments', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=16)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='main.city')),
            ],
        ),
    ]
