# Generated by Django 3.1.4 on 2020-12-24 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201224_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
