# Generated by Django 3.1.4 on 2020-12-24 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201224_1532'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'managed': True, 'ordering': ['price']},
        ),
    ]
