# Generated by Django 3.1.4 on 2020-12-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201224_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='test_field',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
