# Generated by Django 3.1.4 on 2020-12-27 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_property_test_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='test',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
    ]
